// utils/headerMapping.js
const headerMapping = {
  "RequestNo": "en",
  "EmployeeNo": "EmployeeNo",//ไม่มีในดาต้าเบส
  "HN": "hn",
  "prefix": "prefix",
  "first_name": "first_name",
  "last_name": "last_name",
  "AGE": "age",
  "gender": "gender",
  "exam_date": "exam_date",
  "CompanyCode": "company_code",
  "CompanyName": "company_name",
  "Address": "address",
  "Employee_code": "employee_code",
  "section": "section",
  "position": "position",
  "department": "department",
  "english_prefix": "english_prefix",
  "english_first_name": "english_first_name",
  "english_last_name": "english_last_name",
  "card_code": "card_code",
  "passport_code": "passport_code",
  "birth_date": "birth_date",
  "english_address": "english_address",
  "nurse_exam_date": "nurse_exam_date",
  "nurse_exam_by": "nurse_exam_by",
  "phone_number": "phone_number",
  "doctor_license": "doctor_license",
  "language": "language",
  "Pachage": "package",
  "weight": "weight",
  "height": "height",
  "bmi": "bmi",
  "bmi_interpretation": "bmi_interpretation",
  "BpSystolic_blood_pressure": "blood_pressure1",
  "BpDiastolic_blood_pressure": "blood_pressure2",
  "bp_interpretation": "bp_interpretation",
  "pulse": "pulse",
  "pulse_interpretation": "pulse_interpretation",
  "waist": "waist_type",
  "waist_interpretation": "waist",
  "temperature": "temperature",
  "respiration_rate": "respiration_rate",
  "smoking": "smoking",
  "drinking": "drinking",
  "exercising": "exercising",
  "allergies": "allergies",
  "sickness": "sickness",
  "surgeries": "surgeries",
  "family_illness_history": "family_illness_history",
  "hospitalizations": "hospitalizations",
  "accidents": "accidents",
  "past_illness_history": "past_illness_history",
  "pass_disease": "pass_disease",
  "accident_details": "accident_details",
  "job_description": "job_description",
  "right_eye_exam": "left_eye_exam",
  "left_eye_exam": "right_eye_exam",
  "wears_glasses": "wears_glasses",
  "color_blindness": "color_blindness",
  "PE_general": "pe_general",
  "pe_head": "pe_head",
  "pe_head_": "pe_head_",//ไม่มีในดาต้าเบส
  "pe_eyes": "pe_eyes",
  "pe_eyes_": "pe_eyes_",//ไม่มีในดาต้าเบส
  "pe_ears": "pe_ears",
  "pe_ears_": "pe_ears_",//ไม่มีในดาต้าเบส
  "pe_oral_cavity": "pe_oral_cavity",
  "pe_oral_cavity_": "pe_oral_cavity_",//ไม่มีในดาต้าเบส
  "pe_shoulder": "pe_shoulder",//ไม่มีในดาต้าเบส
  "pe_shoulder_": "pe_shoulder_",//ไม่มีในดาต้าเบส
  "pe_leg": "pe_leg",//ไม่มีในดาต้าเบส
  "pe_leg_": "pe_leg_",//ไม่มีในดาต้าเบส
  "pe_lung": "pe_lung",
  "pe_lung_": "pe_lung_",//ไม่มีในดาต้าเบส
  "pe_breasts": "pe_breasts",
  "pe_breasts_": "pe_breasts_",//ไม่มีในดาต้าเบส
  "pe_heart": "pe_heart",
  "pe_heart_": "pe_heart_",//ไม่มีในดาต้าเบส
  "pe_vascular": "pe_vascular",//ไม่มีในดาต้าเบส
  "pe_vascular_": "pe_vascular_",//ไม่มีในดาต้าเบส
  "pe_abdomen_viscera": "pe_abdominal",
  "pe_abdomen_viscera_": "pe_abdomen_viscera_",//ไม่มีในดาต้าเบส
  "pe_musculo": "pe_musculo",//ไม่มีในดาต้าเบส
  "pe_musculo_": "pe_musculo_",//ไม่มีในดาต้าเบส
  "pe_endocine": "pe_endocine",//ไม่มีในดาต้าเบส
  "pe_endocine_": "pe_endocine_",//ไม่มีในดาต้าเบส
  "pe_skin": "pe_skin",
  "pe_skin_": "pe_skin_",//ไม่มีในดาต้าเบส
  "pe_cerebro_neurological_": "pe_cerebro_neurological_",//ไม่มีในดาต้าเบส
  "pe_mental_": "pe_mental_",//ไม่มีในดาต้าเบส
  "pe_throat": "pe_throat",
  "pe_nose": "pe_nose",
  "chest_xray": "chest_xray",
  "chest_xray_summary": "chest_xray_summary",
  "doctor_xray": "doctor_xray",
  "mammogram": "mammogram",
  "mammogram_detail": "mammogram_detail",
  "doctor_mam": "doctor_mam",
  "ultrasound": "upper_ultrasound",
  "ultrasound_detail": "lower_ultrasound",
  "doctor_UL": "doctor_ul",
  "BONE": "BONE",//ไม่มีในดาต้าเบส
  "BONE_detail": "BONE_detail",//ไม่มีในดาต้าเบส
  "doctor_BONE": "doctor_BONE",//ไม่มีในดาต้าเบส
  "CT": "CT",//ไม่มีในดาต้าเบส
  "CT_detail": "CT_detail",//ไม่มีในดาต้าเบส
  "doctor_CT": "doctor_CT",//ไม่มีในดาต้าเบส
  "MRI": "MRI",//ไม่มีในดาต้าเบส
  "MRI_detail": "MRI_detail",//ไม่มีในดาต้าเบส
  "doctor_MRI": "doctor_MRI",//ไม่มีในดาต้าเบส
  "bloodgroup_abo": "bloodgroup_abo",//ไม่มีในดาต้าเบส
  "bloodgroup_abo_Summary": "bloodgroup_abo_Summary",//ไม่มีในดาต้าเบส
  "bloodgroup_rh": "bloodgroup_rh",//ไม่มีในดาต้าเบส
  "bloodgroup_rh_Summary": "bloodgroup_rh_Summary",//ไม่มีในดาต้าเบส
  "ua_color": "ua_color",
  "ua_color_Summary": "ua_color_Summary",//ไม่มีในดาต้าเบส
  "Turbidity": "ua_appearance",
  "Turbidity_Summary": "Turbidity_Summary",//ไม่มีในดาต้าเบส
  "ua_sp_gr": "ua_sp_gr",
  "ua_sp_gr_Summary": "ua_sp_gr_Summary",//ไม่มีในดาต้าเบส
  "ua_ph": "ua_ph",
  "ua_ph_Summary": "ua_ph_Summary",//ไม่มีในดาต้าเบส
  "ua_protein": "ua_protein",
  "ua_protein_Summary": "ua_protein_Summary",//ไม่มีในดาต้าเบส
  "ua_glucose": "ua_glucose",
  "ua_glucose_Summary": "ua_glucose_Summary",//ไม่มีในดาต้าเบส
  "ua_rbc": "ua_rbc",
  "ua_rbc_Summary": "ua_rbc_Summary",//ไม่มีในดาต้าเบส
  "ua_WBC": "ua_wbc",
  "ua_wbc_Summary": "ua_wbc_Summary",//ไม่มีในดาต้าเบส
  "ua_epithelial": "ua_epithelial",
  "ua_epithelial_Summary": "ua_epithelial_Summary",//ไม่มีในดาต้าเบส
  "ua_Amorphous": "ua_Amorphous",//ไม่มีในดาต้าเบส
  "ua_Amorphous_Summary": "ua_Amorphous_Summary",//ไม่มีในดาต้าเบส
  "ua_Cast0": "ua_Cast0",//ไม่มีในดาต้าเบส
  "ua_Cast0_Summary": "ua_Cast0_Summary",//ไม่มีในดาต้าเบส
  "ua_Crystal0": "ua_Crystal0",//ไม่มีในดาต้าเบส
  "ua_Crystal0_Summary": "ua_Crystal0_Summary",//ไม่มีในดาต้าเบส
  "ua_leukocytes": "ua_leukocytes",
  "ua_leukocytes_Summary": "ua_leukocytes_Summary",//ไม่มีในดาต้าเบส
  "ua_ketone": "ua_ketone",
  "ua_ketone_Summary": "ua_ketone_Summary",//ไม่มีในดาต้าเบส
  "ua_nitrite": "ua_nitrite",
  "ua_nitrite_Summary": "ua_nitrite_Summary",//ไม่มีในดาต้าเบส
  "ua_other": "ua_other",//ไม่มีในดาต้าเบส
  "ua_other_Summary": "ua_other_Summary",//ไม่มีในดาต้าเบส
  "pregnancy_test": "pregnancy_test",//ไม่มีในดาต้าเบส
  "pregnancy_test_Summary": "pregnancy_test_Summary",//ไม่มีในดาต้าเบส
  "stool_exam_rbc": "stool_exam_rbc",
  "stool_exam_rbc_Summary": "stool_exam_rbc_Summary",//ไม่มีในดาต้าเบส
  "stool_exam_wbc": "stool_exam_wbc",
  "stool_exam_wbc_Summary": "stool_exam_wbc_Summary",//ไม่มีในดาต้าเบส
  "stool_Epithelium": "stool_epithelium",
  "stool_Epithelium_Summary": "stool_Epithelium_Summary",//ไม่มีในดาต้าเบส
  "stool_exam_parasite": "stool_exam_parasite",
  "stool_exam_parasite_Summary": "stool_exam_parasite_Summary",//ไม่มีในดาต้าเบส
  "stool_exam_other": "stool_exam_other",//ไม่มีในดาต้าเบส
  "stool_exam_other_Summary": "stool_exam_other_Summary",//ไม่มีในดาต้าเบส
  "occult_blood": "occult_blood",//ไม่มีในดาต้าเบส
  "occult_blood_Summary": "occult_blood_Summary",//ไม่มีในดาต้าเบส
  "cbc_hb": "cbc_hb",
  "cbc_hb_Summary": "cbc_hb_summary",
  "cbc_hct": "cbc_hct",
  "cbc_hct_Summary": "cbc_hct_summary",
  "cbc_WBC": "cbc_wbc",
  "cbc_WBC_Summary": "cbc_wbc_summary",
  "cbc_Differential_WBC": "cbc_Differential_WBC",//ไม่มีในดาต้าเบส
  "cbc_Differential_WBC_Summary": "cbc_Differential_WBC_Summary",//ไม่มีในดาต้าเบส
  "cbc_Segmented_Neutrophil": "cbc_neutrophil",
  "cbc_Segmented_Neutrophil_Summary": "cbc_Segmented_Neutrophil_Summary",//ไม่มีในดาต้าเบส
  "cbc_Lymphocyle": "cbc_lymphocyte",
  "cbc_Lymphocyle_Summary": "cbc_lymphocyte_summary",
  "cbc_Monocyle": "cbc_monocyte",
  "cbc_Monocyle_Summary": "cbc_Monocyle_Summary",//ไม่มีในดาต้าเบส
  "cbc_Eosinophil": "cbc_eosinophil",
  "cbc_Eosinophil_Summary": "cbc_eosinophil_summary",
  "cbc_Basopil": "cbc_basophil",
  "cbc_Basopil_Summary": "cbc_Basopil_Summary",//ไม่มีในดาต้าเบส
  "cbc_Atypical_Lymphocyte": "cbc_Atypical_Lymphocyte",//ไม่มีในดาต้าเบส
  "cbc_Atypical_Lymphocyte_Summary": "cbc_Atypical_Lymphocyte_Summary",//ไม่มีในดาต้าเบส
  "cbc_Other": "cbc_Other",//ไม่มีในดาต้าเบส
  "cbc_Other_Summary": "cbc_Other_Summary",//ไม่มีในดาต้าเบส
  "cbc_RBC": "cbc_RBC",//ไม่มีในดาต้าเบส
  "cbc_RBC_Summary": "cbc_RBC_Summary",//ไม่มีในดาต้าเบส
  "cbc_MCV": "cbc_mvc",
  "MCV_Summary": "cbc_mvc_summary",
  "cbc_MCH": "mch",
  "MCH_Summary": "MCH_Summary",//ไม่มีในดาต้าเบส
  "MCHC": "mchc",
  "MCHC_Summary": "MCHC_Summary",//ไม่มีในดาต้าเบส
  "RDW": "rdw",
  "RDW_Summary": "RDW_Summary",//ไม่มีในดาต้าเบส
  "RBC": "rbc",
  "RBC_Summary": "RBC_Summary",//ไม่มีในดาต้าเบส
  "Platetet": "cbc_platelet_count",
  "Platetet_Summary": "cbc_platelet_count_summary",
  "Other2": "Other2",//ไม่มีในดาต้าเบส
  "Other2_Summary": "Other2_Summary",//ไม่มีในดาต้าเบส
  "FBS": "fbs",
  "FBS_Summary": "fbs_detail",
  "HbA1c": "hba1c",
  "HbA1c_Summary": "hba1c_detail",
  "BUN": "bun",
  "BUN_Summary": "bun_detail",
  "Ccreatinine": "creatinine",
  "Ccreatinine_Summary": "creatinine_detail",
  "eGFR": "egfr",
  "eGFR_Summary": "egfr_detail",
  "uric_acid": "uric_acid",
  "uric_acid_Summary": "uric_detail",
  "cholesterol": "cholesterol",
  "cholesterol_Summary": "chol_detail",
  "hdl_cholesterol": "hdl_cholesterol",
  "hdl_cholesterol_Summary": "hdl_detail",
  "Triglyceride": "triglyceride",
  "Triglyceride_Summary": "triglyceride_detail",
  "ldl_cholesterol_Calculate": "ldl_cholesterol",
  "ldl_cholesterol_Calculate_Summary": "ldl_detail",
  "ldl_cholesterol_Direct": "ldl_cholesterol_Direct",//ไม่มีในดาต้าเบส
  "ldl_cholesterol_Direct_Summary": "ldl_cholesterol_Direct_Summary",//ไม่มีในดาต้าเบส
  "CheckUpMethod": "CheckUpMethod",//ไม่มีในดาต้าเบส
  "conclusion": "conclusion",
  "recommendation": "recommendation",
  "RECOM1": "physical_exam_summary", //อันใหม่
  "RECOM3": "ua_summary", //อันใหม่
  "RECOM7": "stool_exam_detail", //อันใหม่
  "RECOM14": "cbc", //อันใหม่
  "RECOM16": "fbs_detail", //อันใหม่
  "RECOM18": "hba1c_detail", //อันใหม่
  "RECOM20": "kidney_summary", //อันใหม่
  "RECOM22": "uric_detail", //อันใหม่
  "RECOM24": "lipid", //อันใหม่
  "RECOM26": "liver1", //อันใหม่
  "RECOM30": "thyroid_detection_detail", //อันใหม่
  "Platelets": "platelet_count", //อันใหม่

  "pe_cerebro_neurological": "pe_nervous_system", //อันใหม่
  "pe_mental": "pe_emotion", //อันใหม่
};

export default headerMapping;